apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon-backend
  template:
    metadata:
      labels:
        app: hackathon-backend
    spec:
      containers:
        - name: hackathon-backend
          image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
          ports:
            - containerPort: {{ .Values.api.service.port }}
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          env:
            - name: DATABASE_URL
              value: {{ .Values.api.env.DATABASE_URL }}
            - name: AWS_REGION
              value: {{ .Values.api.env.AWS_REGION }}
            - name: AWS_S3_BUCKET
              value: {{ .Values.api.env.AWS_S3_BUCKET }}
            - name: SQS_QUEUE_URL
              value: {{ .Values.api.env.SQS_QUEUE_URL }}
            - name: NOTIFICATION_QUEUE_URL
              value: {{ .Values.api.env.NOTIFICATION_QUEUE_URL }}
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.api.env.AWS_ACCESS_KEY_ID }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.api.env.AWS_SECRET_ACCESS_KEY }}
            - name: AWS_SESSION_TOKEN
              value: {{ .Values.api.env.AWS_SESSION_TOKEN }}
